package com.kafkaantidote.reinject;

import com.kafkaantidote.core.RawMessage;
import com.kafkaantidote.core.ReinjectionPlan;
import com.kafkaantidote.core.TopicPartitionOffset;
import java.util.Base64;
import java.util.Map;

/**
 * Generates the safe re-injection artifact (Spec R4). Pure — depends only on the {@code core} value
 * types, produces a Java-source string, and performs NO I/O and NO Kafka calls itself.
 *
 * <p>The generated artifact is a self-contained {@code kafka-clients} producer program that:
 * <ul>
 *   <li>targets the EXACT original partition via the explicit-partition {@code ProducerRecord}
 *       constructor — never key-hash re-partitioning (R4.2), with a runtime assertion to match;</li>
 *   <li>preserves the original key and headers, replacing only the value with the operator-corrected
 *       payload (R4.1);</li>
 *   <li>only ever produces a single message — it never seeks, commits, or advances any consumer
 *       offset (R4.3), and does not unstick the group (R4.6);</li>
 *   <li>defaults to DRY RUN and requires the explicit {@code --produce --yes} flags to send
 *       (R4.4);</li>
 *   <li>carries a warning header telling the operator to review it and fix the root cause first
 *       (R4.5).</li>
 * </ul>
 */
public final class ReinjectionScriptGenerator {

    private static final Base64.Encoder B64 = Base64.getEncoder();

    private ReinjectionScriptGenerator() {
    }

    public static ReinjectionPlan generate(RawMessage original, byte[] correctedPayload,
                                           String bootstrapServers) {
        TopicPartitionOffset target = original.position();
        String script = buildJavaSource(target, original.key(), original.headers(),
                correctedPayload, bootstrapServers);
        return new ReinjectionPlan(target, "java", script);
    }

    private static String buildJavaSource(TopicPartitionOffset target, byte[] key,
                                          Map<String, byte[]> headers, byte[] value,
                                          String bootstrapServers) {
        String keyLiteral = key == null ? "null" : '"' + B64.encodeToString(key) + '"';
        String valueB64 = B64.encodeToString(value);

        StringBuilder headerRows = new StringBuilder();
        for (Map.Entry<String, byte[]> h : headers.entrySet()) {
            headerRows.append("        {\"").append(escape(h.getKey())).append("\", \"")
                    .append(B64.encodeToString(h.getValue())).append("\"},\n");
        }

        StringBuilder s = new StringBuilder();
        s.append("/*\n");
        s.append(" * ============================================================================\n");
        s.append(" *  SAFE RE-INJECTION SCRIPT  --  generated by Kafka Antidote\n");
        s.append(" * ============================================================================\n");
        s.append(" *  WARNING: A human MUST review this script before running it, and MUST fix the\n");
        s.append(" *  ROOT CAUSE first (the producer bug or schema change that created the poison\n");
        s.append(" *  pill). Running this without fixing the cause will just create another one.\n");
        s.append(" *\n");
        s.append(" *  This re-injects a CORRECTED message to the EXACT original partition,\n");
        s.append(" *  preserving the original key and headers. It produces exactly ONE message.\n");
        s.append(" *  It does NOT skip, seek, or commit any consumer offset, and it does NOT\n");
        s.append(" *  unstick the consumer group -- that is a separate, deliberate action you take.\n");
        s.append(" *\n");
        s.append(" *  Target : ").append(escape(target.topic())).append("-").append(target.partition())
                .append("  (original offset ").append(target.offset()).append(", for reference only)\n");
        s.append(" *\n");
        s.append(" *  Usage:\n");
        s.append(" *    Dry run (default -- produces nothing):\n");
        s.append(" *      java -cp kafka-clients.jar Reinject.java\n");
        s.append(" *    Actually produce (requires BOTH flags, after review):\n");
        s.append(" *      java -cp kafka-clients.jar Reinject.java --produce --yes\n");
        s.append(" * ============================================================================\n");
        s.append(" */\n");
        s.append("import org.apache.kafka.clients.producer.KafkaProducer;\n");
        s.append("import org.apache.kafka.clients.producer.ProducerConfig;\n");
        s.append("import org.apache.kafka.clients.producer.ProducerRecord;\n");
        s.append("import org.apache.kafka.clients.producer.RecordMetadata;\n");
        s.append("import org.apache.kafka.common.serialization.ByteArraySerializer;\n");
        s.append("import java.util.Base64;\n");
        s.append("import java.util.Properties;\n\n");
        s.append("public class Reinject {\n");
        s.append("    static final String BOOTSTRAP = \"").append(escape(bootstrapServers)).append("\";\n");
        s.append("    static final String TOPIC     = \"").append(escape(target.topic())).append("\";\n");
        s.append("    static final int    PARTITION = ").append(target.partition())
                .append(";   // EXACT original partition -- no key-hash re-partitioning (R4.2)\n");
        s.append("    static final long   ORIGINAL_OFFSET = ").append(target.offset())
                .append("L; // reference only -- never seeked or committed (R4.3)\n");
        s.append("    static final String KEY_B64   = ").append(keyLiteral)
                .append(";  // original key (base64) or null\n");
        s.append("    static final String VALUE_B64 = \"").append(valueB64)
                .append("\"; // operator-corrected payload (base64)\n");
        s.append("    static final String[][] HEADERS = {\n");
        s.append(headerRows);
        s.append("    };\n\n");
        s.append("    public static void main(String[] args) throws Exception {\n");
        s.append("        boolean produce = has(args, \"--produce\") && has(args, \"--yes\");\n");
        s.append("        byte[] key   = KEY_B64 == null ? null : Base64.getDecoder().decode(KEY_B64);\n");
        s.append("        byte[] value = Base64.getDecoder().decode(VALUE_B64);\n\n");
        s.append("        System.out.println(\"Re-injection target: \" + TOPIC + \"-\" + PARTITION\n");
        s.append("                + \"  (original offset \" + ORIGINAL_OFFSET + \")\");\n");
        s.append("        System.out.println(\"Payload: \" + value.length + \" bytes; key: \"\n");
        s.append("                + (key == null ? \"<null>\" : key.length + \" bytes\")\n");
        s.append("                + \"; headers: \" + HEADERS.length);\n\n");
        s.append("        if (!produce) {\n");
        s.append("            System.out.println();\n");
        s.append("            System.out.println(\"DRY RUN -- nothing was produced.\");\n");
        s.append("            System.out.println(\"Re-run with  --produce --yes  to actually send (after review).\");\n");
        s.append("            return;\n");
        s.append("        }\n\n");
        s.append("        Properties p = new Properties();\n");
        s.append("        p.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, BOOTSTRAP);\n");
        s.append("        p.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, ByteArraySerializer.class.getName());\n");
        s.append("        p.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, ByteArraySerializer.class.getName());\n");
        s.append("        p.put(ProducerConfig.ACKS_CONFIG, \"all\");\n");
        s.append("        try (KafkaProducer<byte[], byte[]> producer = new KafkaProducer<>(p)) {\n");
        s.append("            // Explicit partition -> lands on PARTITION regardless of key hashing (R4.2).\n");
        s.append("            ProducerRecord<byte[], byte[]> record = new ProducerRecord<>(TOPIC, PARTITION, key, value);\n");
        s.append("            for (String[] h : HEADERS) {\n");
        s.append("                record.headers().add(h[0], Base64.getDecoder().decode(h[1]));\n");
        s.append("            }\n");
        s.append("            RecordMetadata md = producer.send(record).get();\n");
        s.append("            if (md.partition() != PARTITION) {\n");
        s.append("                throw new IllegalStateException(\"SAFETY CHECK FAILED: landed on partition \"\n");
        s.append("                        + md.partition() + \", expected \" + PARTITION);\n");
        s.append("            }\n");
        s.append("            System.out.println(\"Produced corrected message to \" + md.topic() + \"-\"\n");
        s.append("                    + md.partition() + \"@\" + md.offset());\n");
        s.append("        }\n");
        s.append("    }\n\n");
        s.append("    static boolean has(String[] args, String flag) {\n");
        s.append("        for (String a : args) { if (a.equals(flag)) return true; }\n");
        s.append("        return false;\n");
        s.append("    }\n");
        s.append("}\n");
        return s.toString();
    }

    private static String escape(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
